config/routes.rb
Tickytime::Application.routes.draw do

  get "course_modules/index"

  get "course_modules/new"

  get "course_modules/edit"

  root :to => "lessons#index"

  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  match '/calendar' => 'calendar#index', :via => :get
  match '/calendar/upload' => 'calendar#upload', :via => :post
  match '/calendar/google_upload' => 'calendar#google_upload'

  resources :activities
  resources :lessons
  resources :course_modules, :path => "modules"

end

app/models/course_module.rb
class CourseModule < ActiveRecord::Base
  attr_accessible :code, :title

  validates :code, :uniqueness => true

  has_many :lessons

end

app/controllers/course_modules_controller.rb
class CourseModulesController < InheritedResources::Base

  def update
    update! do |success, failure|
      failure.html {
        flash[:notice] = "Error updating module"
      }
      success.html { redirect_to course_modules_path }
    end
  end

end

app/views/course_modules/_course_module.html.erb
<article class="lesson">
  <% if course_module.title.present? %>
    <%= content_tag :h3, course_module.title, :class => "lesson-title" %>
    <span class="course-module"><%= course_module.code %></span>
  <% else -%>
    <%= content_tag :h3, course_module.code, :class => "lesson-title" %>
  <% end -%>
  <%= link_to "Edit", edit_course_module_path(course_module.id) %>
</article>

app/views/course_modules/_form.html.erb
<%= form_for(@course_module) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end -%>

app/views/course_modules/edit.html.erb
<%= page_title "Edit #{@course_module.code}" %>
<%= render "form" %>

app/views/course_modules/index.html.erb
<%= page_title "Modules" %>
<%= render @course_modules %>

app/views/course_modules/new.html.erb
<h1>CourseModules#new</h1>
<p>Find me in app/views/course_modules/new.html.erb</p>