config/routes.rb
Tickytime::Application.routes.draw do

  get "course_modules/index"

  get "course_modules/new"

  get "course_modules/edit"

  root :to => "lessons#index"

  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  match '/calendar' => 'calendar#index', :via => :get
  match '/calendar/upload' => 'calendar#upload', :via => :post
  match '/calendar/google_upload' => 'calendar#google_upload'

  resources :activities
  resources :lessons
  resources :course_modules, :path => "modules"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :course_module_id, :end_at, :groups, :room, :start_at, :title, :lesson_type, :user_id

  validates_presence_of :start_at, :end_at, :title

  belongs_to :course_module
  has_one :user

  def self.build_from_csv(row)

    puts row.inspect

    # find existing lesson from email or create new
    lesson = find_or_initialize_by_start_at("#{row["Date"]} #{row["Start"]}")
    lesson.attributes ={
      :course_module_id => row["Code"],
      :end_at => "#{row["Date"]} #{row["End"]}",
      :groups => row["Groups"],
      :room => row["Room"],
      :start_at => "#{row["Date"]} #{row["Start"]}",
      :title => row["Title"],
      :lesson_type => row["Type"],
      :user_id => row["User_id"]
    }
    #return lesson

    if lesson.valid?
      lesson.save
    else
      #errs << row
    end

  end

  def self.by_day
    all.group_by { |l| l.start_at.to_date.to_s(:db) }
  end

  def self.all_from_now
    where(["start_at >= ?", Time.now])
  end

  def self.current_week
    where("end_at >= ? AND end_at <= ?", Time.now, (Time.now + 1.week))
  end

  def self.current_month
    where("end_at >= ? AND end_at <= ?", Time.now, (Time.now + 1.month))
  end

  def calculate_break(lessons)
    unless lessons.nil?
      index = lessons.find_index(self)
      (self.start_at - lessons[index-1].end_at) if index > 0
    end
  end

  def duration
    Time.at(end_at - start_at).utc.strftime("%k:%M")
  end

end

app/controllers/lessons_controller.rb
class LessonsController < InheritedResources::Base

  def index

    if current_user.present?
      if params["timeframe"] == "all"
        @lessons = current_user.lessons.by_day
      elsif params["timeframe"] == "month"
        @lessons = current_user.lessons.current_month.by_day
      else
        @lessons = current_user.lessons.current_week.by_day
      end
    end
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper

  def render_break(lesson, lessons)
    gap = lesson.calculate_break(lessons)
    render :partial => "gap", :locals => {:gap => gap} if gap.to_i > 0
  end

  def lesson_daytime_summary(lessons)
    "#{lessons.first.start_at.strftime("%a %d %b")} #{spanerize(format_hour(lessons.first.start_at) + " - " + (format_hour(lessons.last.end_at)))}".html_safe
  end

  def lesson_start_end(lesson)
    "#{format_hour(lesson.start_at)} - #{format_hour(lesson.end_at)} #{spanerize(lesson.duration)}".html_safe
  end

end

app/views/lessons/_lesson.html.erb
<article class="lesson">
  <%= time_tag lesson.start_at, lesson_start_end(lesson), :class => "lesson-time-info" %>
  <h3 class="lesson-title"><%= lesson.title %></h3>
  <span class="course-module"><%= lesson.course_module.title.present? ? lesson.course_module.title : lesson.course_module.code %></span>
</article>

app/views/lessons/_lessons.html.erb
<% @lessons.each do |day, lessons| %>
  <div class="lesson-by-day">
    <h2>
      <%= time_tag lessons.first.start_at, lesson_daytime_summary(lessons), :class=>"lesson-time-info" %>
    </h2>
    <div>
      <% lessons.each_with_index do |lesson, index| %>
        <%= render_break(lesson, lessons) %>
        <%= render lesson %>
      <% end -%>
    </div>
  </div>
<% end -%>

app/views/lessons/index.html.erb
<% if @lessons.present? && @lessons.any? %>

  <%= page_title("Lessons") %>

  <%= form_tag(lessons_url, :id => "lessons_timeframe_form", :class => "lessons-timeframe-form", :method => "get") do %>
    <ul class="in-list right">
      <li>
        <%= radio_button_tag "timeframe", "week", params[:timeframe] != "month" && params[:timeframe] != "all" %>
        <%= label_tag "timeframe_week", "Week" %>
      </li>
      <li>
        <%= radio_button_tag "timeframe", "month", params[:timeframe] == "month" %>
        <%= label_tag "timeframe_month", "Month" %>
      </li>
      <li>
        <%= radio_button_tag "timeframe", "all", params[:timeframe] == "all" %>
        <%= label_tag "timeframe_all", "All" %>
      </li>
    </ul>

    <%= submit_tag "change timeframe", :class => "timeframe-submit-btn" %>
  <% end -%>

  <%= render "lessons" %>

<% elsif current_user.present? %>

  <h1>Upload your lesson plan to get started</h1>
  <%= render "calendar/form" %>
<% else -%>
  <h1><%= link_to "Sign in  with your google account to get started", "/auth/google_oauth2" %></h1>
<% end -%>