config/routes.rb
Tickytime::Application.routes.draw do

  get "course_modules/index"

  get "course_modules/new"

  get "course_modules/edit"

  root :to => "lessons#index"

  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  match '/calendar' => 'calendar#index', :via => :get
  match '/calendar/upload' => 'calendar#upload', :via => :post
  match '/calendar/google_upload' => 'calendar#google_upload'

  resources :activities
  resources :lessons
  resources :course_modules, :path => "modules"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :start_at, :end_at, :notes, :is_completed

  validates_presence_of :title, :start_at, :end_at
end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base

end

app/views/activities/_activity.html.erb
<%= activity.title %>
<%= activity.start_at %>
<%= activity.end_at %>
<%= activity.notes %>
<%= activity.is_completed %>

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <ul class="fields">
    <li class="field text">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li class="field time">
      <%= f.label :start_at %>
      <%= f.text_field :start_at %>
    </li>
    <li class="field time">
      <%= f.label :end_at %>
      <%= f.text_field :end_at %>
    </li>
    <li class="field text">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </li>
    <li class="field boolean">
      <%= f.check_box :is_completed %>
      <%= f.label :is_completed %>
    </li>
  </ul>

  <%= f.submit %>
<% end -%>

app/views/activities/edit.html.erb
<%= page_title "Edit activity" %>
<%= render "form" %>

app/views/activities/index.html.erb
<%= link_to "New Activity", new_activity_path %>

app/views/activities/new.html.erb
<%= page_title "New activity" %>
<%= render "form" %>

app/views/activities/show.html.erb
<%= page_title @activity.title %>
<%= render @activity %>