config/routes.rb
Tickytime::Application.routes.draw do

  get "course_modules/index"

  get "course_modules/new"

  get "course_modules/edit"

  root :to => "lessons#index"

  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'
  match "/signout" => "sessions#destroy", :as => :signout

  match '/calendar' => 'calendar#index', :via => :get
  match '/calendar/upload' => 'calendar#upload', :via => :post
  match '/calendar/google_upload' => 'calendar#google_upload'

  resources :activities
  resources :lessons
  resources :course_modules, :path => "modules"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><% if content_for?(:title) %><%= yield(:title) %> | <% end %>TickyTime</title>
    <meta name="description" content="">

    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta http-equiv="cleartype" content="on">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "modernizr-2.6.2.js" %>
  </head>

  <body class="<%=controller_name%>-<%= action_name %>" id="<%= controller_name %>" data-action="<%= action_name %>">
    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->
    <%= content_tag(:section, content_tag(:p, notice), :class => "flash notice") if notice %>
    <%= content_tag(:section, content_tag(:p, alert), :class => "flash alert") if alert %>

    <header class="site-header">
      <nav class="user-nav left">
        <% if current_user %>
          <%= link_to "Sign Out", signout_path %>
        <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
        <% end %>
      </nav>
      <% if current_user %>
        <nav class="main-nav right">
          <ul class="in-list">
            <li><%= link_to "Calendar upload", calendar_path %></li>
            <li><%= link_to "Lessons", lessons_path %></li>
            <li><%= link_to "Modules", course_modules_path %></li>
            <!-- <li><%= link_to "Activities", activities_path %></li> -->
          </ul>
        </nav>
      <% end -%>
    </header>

    <div class="content-area clear">
      <%= yield %>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<%= asset_path("jquery-1.8.2.js") %>"><\/script>')</script>
    <%= javascript_include_tag "application" %>

    <%= yield :page_js %>

    <script>
      var _gaq=[['_setAccount','UA-XXXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
  </body>
</html>